train:
    env:                                "highway_environment:highway-environment-v0"
    run:                                PPO
    checkpoint_freq:                    50
    checkpoint_at_end:                  true

    stop:
        training_iteration:             300

    config:
        horizon:                        200
        framework:                      torch
        env:                            "highway_environment:highway-environment-v0"
        gamma:                          0.95
        lr:                             0.0003
        num_gpus:                       0.5
        num_workers:                    1
        num_gpus_per_worker:            0.5
        num_envs_per_worker:            1
        num_sgd_iter:                   10
        entropy_coeff:                  0.001
        evaluation_interval:            1
        evaluation_num_episodes:        50
        evaluation_num_workers:         0
        
        model:
            use_lstm: true
            lstm_cell_size:             64
            max_seq_len:                20
            fcnet_hiddens:              [ 64, 64 ]
            vf_share_layers:            false
